MODEL:
  PRETRAIN_PATH : '../../pretrained_models'
  NAME: 'resnet50_ibn_a'
  NECK: 'bnneck'
  NETWORK: LTE_CNN
  IF_LABELSMOOTH: 'on'
  #IF_WITH_CENTER: 'yes'
  #METRIC_LOSS_TYPE: 'triplet'

  #Evaluate: "both"
  Evaluate: "ClothChangingSetting"
  #Evaluate: "StandardSetting" # When DATASETS.CAMER='B', you must set the MODEL.Evaluate as "StandardSetting"

INPUT:
#  SIZE_TRAIN: [512, 256]
#  SIZE_TEST: [512, 256]
  SIZE_TRAIN: [ 256, 128 ]
#  SIZE_TEST: [ 256, 128 ]
#  SIZE_TRAIN: [ 32, 16 ]
#  SIZE_TEST: [ 32, 16 ]
  PADDING : 10

DATASETS:
  NAMES: ('prcc_orig_shu2021') # ltcc_noneID, ltcc_orig, celebreid_noneID, celebreid_orig, prcc_noneID, prcc_orig, nkup_noneID, nkup_orig, prcc_orig_shu2021

  #ROOT_DIR: "/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/B_DATASETS/Long_term_datasets/NKUP/NKUP_orig"
  #feat2_DIR: "/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/B_DATASETS/Long_term_datasets/NKUP/NKUP_STE_features"

  #ROOT_DIR: '/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/A_PROJECTS/LOCAL/cvpr2021/YLD_YouLookDifferent/OUTPUT/tsne/Onefolder_test_images_20ids_limit_to_20_imgs_for_each_clothe'
  #feat2_DIR: "/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/B_DATASETS/Long_term_datasets/LTCC_ReID/LTCC_nonID/STE_features"
  #feat2_DIR: /media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/B_DATASETS/Long_term_datasets/LTCC_ReID/LTCC_nonID/NewImgs_feat2_by_N1

  #feat2_DIR: '/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/B_DATASETS/Long_term_datasets/prcc/prcc_nonID/STE_features'
  feat2_DIR: '/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/B_DATASETS/Long_term_datasets/prcc/prcc_nonID/AC_best_extracted_features_by_N1'
  ROOT_DIR: '/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/B_DATASETS/Long_term_datasets/prcc/prcc_orig'
  CAMERA: C # B or C

  #ROOT_DIR: '/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/B_DATASETS/Long_term_datasets/celeb_reid/celebreid_orig'
  #feat2_DIR: '/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/B_DATASETS/Long_term_datasets/celeb_reid/celebreid_nonID/extracted_features_by_N1'

DATALOADER:
  SAMPLER: 'softmax_CosineSim'
  Aug: True

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 128

  STEPS: [30, 55]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5
  WARMUP_METHOD: 'linear'

  MAX_EPOCHS: 150
  CHECKPOINT_PERIOD: 5
  LOG_PERIOD: 50
  EVAL_PERIOD: 5


TEST:
  IMS_PER_BATCH: 128
  NECK_FEAT: 'after'
  RE_RANKING: 'no'
  WEIGHT: "/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/A_PROJECTS/LOCAL/cvpr2021/You-Look-So-Different-Haven-t-I-Seen-You-a-Long-Time-Ago/OUTPUT/LTE_CNN_prcc_orig_shu2021/train_2021_Aug_28_09_40_14/resnet50_ibn_a_model_50_best.pth"
  #WEIGHT: "/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/A_PROJECTS/LOCAL/cvpr2021/You-Look-So-Different-Haven-t-I-Seen-You-a-Long-Time-Ago/OUTPUT/LTE_CNN_nkup/train_2021_Aug_27_19_52_37/resnet50_ibn_a_model_90.pth"
  #WEIGHT : '/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/A_PROJECTS/LOCAL/cvpr2021/You-Look-So-Different-Haven-t-I-Seen-You-a-Long-Time-Ago/OUTPUT/LTE_CNN_nkup/train_2021_Aug_27_11_32_19/senet154_model_5_best.pth'
  #WEIGHT : '/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/A_PROJECTS/LOCAL/cvpr2021/YLD_YouLookDifferent/OUTPUT/Network2/Ablation_senet154/train_2021_Mar_17_12_13_23/senet154_model_40.pth' # ablation with size 256*128
  #WEIGHT: '/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/A_PROJECTS/LOCAL/cvpr2021/YLD_YouLookDifferent/OUTPUT/Network2/Ablation_senet154/train_2021_Mar_18_21_53_36/senet154_model_45.pth' # ablation with size 512*256

OUTPUT_DIR: "/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/A_PROJECTS/LOCAL/cvpr2021/You-Look-So-Different-Haven-t-I-Seen-You-a-Long-Time-Ago/OUTPUT/LTE_CNN_prcc_orig_shu2021"



