MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  NAME: 'senet154'
  PRETRAIN_PATH: '../pretrained_models'
  NETWORK: "simple_baseline"
  Evaluate: "both" # "both" or "StandardSetting" or "ClothChangingSetting" #Note: When DATASETS.CAMER='B', you must set the MODEL.Evaluate as "StandardSetting"

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PADDING : 10

DATASETS:
  NAMES: ('nkup_orig') # ltcc_noneID, ltcc_orig, celebreid_noneID, celebreid_orig, prcc_noneID, prcc_orig, nkup_noneID, nkup_orig
  #CAMERA: B

  #ROOT_DIR: '/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/B_DATASETS/Long_term_datasets/celeb_reid/celebreid_orig'
  #ROOT_DIR: '/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/B_DATASETS/Long_term_datasets/prcc/prcc_orig'
  #ROOT_DIR: '/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/B_DATASETS/Long_term_datasets/LTCC_ReID/LTCC_orig'
  ROOT_DIR: "/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/B_DATASETS/Long_term_datasets/NKUP/NKUP_orig"

  feat2_DIR: "None"

DATALOADER:
  SAMPLER: 'softmax'
  Aug: True

SOLVER:
  MAX_EPOCHS: 50
  IMS_PER_BATCH: 16
  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 50
  EVAL_PERIOD: 1

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: 'no'
  WEIGHT: "/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/A_PROJECTS/LOCAL/cvpr2021/You-Look-So-Different-Haven-t-I-Seen-You-a-Long-Time-Ago/OUTPUT/simple_baseline_nkup/train_2021_Aug_28_00_50_08/senet154_model_50.pth"

OUTPUT_DIR: "/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/A_PROJECTS/LOCAL/cvpr2021/You-Look-So-Different-Haven-t-I-Seen-You-a-Long-Time-Ago/OUTPUT/simple_baseline_nkup"


