MODEL:
  PRETRAIN_PATH: '../pretrained_models'
  NECK: 'bnneck'
  IF_LABELSMOOTH: 'on'
  NETWORK: "strong_baseline"
  Evaluate: "both" # "both" or "StandardSetting" or "ClothChangingSetting" #Note: When DATASETS.CAMER='B', you must set the MODEL.Evaluate as "StandardSetting"


INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PADDING : 10

DATASETS:
  NAMES: ('nkup_orig') # ltcc_noneID, ltcc_orig, celebreid_noneID, celebreid_orig, prcc_noneID, prcc_orig, nkup_noneID, nkup_orig
  #CAMERA: B

  #ROOT_DIR: '/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/B_DATASETS/Long_term_datasets/celeb_reid/celebreid_orig'
  #ROOT_DIR: '/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/B_DATASETS/Long_term_datasets/prcc/prcc_orig'
  #ROOT_DIR: '/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/B_DATASETS/Long_term_datasets/LTCC_ReID/LTCC_orig'
  ROOT_DIR: "/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/B_DATASETS/Long_term_datasets/NKUP/NKUP_orig"

  #ROOT_DIR: '/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/A_PROJECTS/LOCAL/cvpr2021/YLD_YouLookDifferent/OUTPUT/tsne/Onefolder_test_images_20ids_limit_to_20_imgs_for_each_clothe'

  feat2_DIR: "None"

DATALOADER:
  SAMPLER: 'softmax'
  Aug: True

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 128

  STEPS: [30, 55]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 5
  WARMUP_METHOD: 'linear'

  MAX_EPOCHS: 50
  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 50
  EVAL_PERIOD: 1

TEST:
  IMS_PER_BATCH: 128
  NECK_FEAT: 'after'
  WEIGHT: ''

Train_on_ShortTerm_data: False

OUTPUT_DIR: "/media/socialab157/2cbae9f1-6394-4fa9-b963-5ef890eee044/A_PROJECTS/LOCAL/cvpr2021/You-Look-So-Different-Haven-t-I-Seen-You-a-Long-Time-Ago/OUTPUT/strong_baseline_nkup"


